### PR TITLE
Avoid fetch only 100 teams

### LINKED ISSUE #766: Error: Unable to find Team with name [<Team Name>] in project with ID [<Project ID>]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform plan is failing to fetch Team Id for some ADO Team but able to fetch other
All ADO Teams have same setting and configurations.

The Azure DevOps Rest endpoint TF is using is only returning a count of 100 teams but our organisation has more

API:
GET https://dev.azure.com/{organization}/_apis/teams?api-version=6.0-preview.3

### Terraform (and Azure DevOps Provider) Version

TF version - 3.22.0
TF ADO version - 0.5.0

### Affected Resource(s)

data sources
* `azuredevops_team`

### Terraform Configuration Files

```
Data.tf

data "azuredevops_team" "security_teams" {
  for_each   = toset(var.ado_repositories_details[*].ado_security_team)
  project_id = data.azuredevops_project.airnz_project.id
  name       = each.value
}

Terraform.tfvars

ado_repositories_details = [
  {
    name              = "testapp1"
    ado_security_team = "<TEAM1>"
  },
  {
    name              = "testapp2"
    ado_security_team = "<TEAM2>"
  },
  {
    name              = "testapp3"
    ado_security_team = "<TEAM1>"
  },
  {
    name              = "testapp4"
    ado_security_team = "<TEAM3>"
  }
]

```

### Debug Output

TF Init :

Initializing provider plugins...
- Reusing previous version of microsoft/azuredevops from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing microsoft/azuredevops v0.5.0...
- Installed microsoft/azuredevops v0.5.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Installing hashicorp/aws v3.22.0...
- Installed hashicorp/aws v3.22.0 (signed by HashiCorp)

TF Plan: 

data.azuredevops_team.security_teams["<TEAM2>"]: Read complete after 1s [id=<>]
data.azuredevops_team.security_teams["<TEAM1>"]: Read complete after 2s [id=<>]

│ Error: Unable to find Team with name [<TEAM3>] in project with ID [<>]
│ 
│   with data.azuredevops_team.security_teams["<TEAM3>"],
│   on data.tf line 8, in data "azuredevops_team" "security_teams":
│    8: data "azuredevops_team" "security_teams" {

### Expected Behavior

TF plan is generated

### Actual Behavior

Error :  Unable to find Team with name

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

### PR DESCRIPTION
**Pull request by ricardosequeira**
## All Submissions:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] I have updated the documentation accordingly.
* [X] I have added tests to cover my changes.
* [X] All new and existing tests passed.
* [X] My code follows the code style of this project.
* [X] I ran lint checks locally prior to submission.
* [X] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number: #766

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [] Yes
- [X] No

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

Closes #766

### CODE REVIEW

**Comment by ricardosequeira** [comment]
@microsoft-github-policy-service agree

**Comment by xuzhang3** [comment]
@ricardosequeira  Some ORGs may  have hundreds or thousands of teams. Get all teams at the same time may took a long time and cause performance issue. Can you refactor the top to a custom value with default values like 100?

**Comment by ricardosequeira** [comment]
@xuzhang3, can you review this PR again?

File: azuredevops/internal/service/core/data_team.go [hunk 1]
```diff
@@ -61,7 +61,15 @@ func dataTeamRead(d *schema.ResourceData, m interface{}) error {
 	projectID := d.Get("project_id").(string)
 	teamName := d.Get("name").(string)
 
-	team, members, administrators, err := readTeamByName(d, clients, projectID, teamName)
+	var top int
+	data, ok := d.GetOk("top")
```
Comment (xuzhang3) [inline azuredevops/internal/service/core/data_team.go]: `top` should be defined in the schema like other property.
Ref: https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/core/data_team.go#L16

**Review by xuzhang3 — CHANGES_REQUESTED** [review]

**Comment by xuzhang3** [comment]
@ricardosequeira  please add the `top`  to the schema. Also you need update the document too.

**Comment by ricardosequeira** [comment]
> @ricardosequeira please add the `top` to the schema. Also you need update the document too.

@xuzhang3, done

File: azuredevops/internal/service/core/data_team.go [hunk 2]
```diff
@@ -61,7 +65,15 @@ func dataTeamRead(d *schema.ResourceData, m interface{}) error {
...
+	if ok {
+		top = data.(int)
+	} else {
+		top = 2147483647
+	}
```
Comment (xuzhang3) [inline azuredevops/internal/service/core/data_team.go]: With default value in the schema,  this code snippet can change to `top := d.Get('top')`

File: azuredevops/internal/service/core/data_teams.go [hunk 3]
```diff
@@ -86,12 +86,21 @@ func dataTeamsRead(d *schema.ResourceData, m interface{}) error {
 			ToSlice(&projectIDList)
 	}
 
+	var top int
+	topData, topOk := d.GetOk("top")
+	if topOk {
+		top = topData.(int)
+	} else {
+		top = 2147483647
+	}
```
Comment (xuzhang3) [inline azuredevops/internal/service/core/data_teams.go]: Add `top` to the schema like `data_team` does:
```go
"top": {
				Type:         schema.TypeInt,
				Optional:     true,
				Default:      100,
				ValidateFunc: validation.IntAtLeast(1),
			},
```

```suggestion
	top := d.Get("top")
```

File: azuredevops/internal/service/core/data_team.go [hunk 4]
```diff
@@ -51,6 +51,10 @@ func DataTeam() *schema.Resource {
 				Type:     schema.TypeString,
 				Computed: true,
 			},
+			"top": {
+				Type:         schema.TypeInt,
+				ValidateFunc: validation.IntAtLeast(1),
+			},
```
Comment (xuzhang3) [inline azuredevops/internal/service/core/data_team.go]: Add a default  value for `top`  (`Default: 100,`) in case user not specified. Otherwise the the hard coded value `2147483647` this will cause performance issue.

```suggestion
			"top": {
				Type:         schema.TypeInt,
				Optional:     true,
				Default:      100,
				ValidateFunc: validation.IntAtLeast(1),
			},
```

File: website/docs/d/data_team.html.markdown [hunk 5]
```diff
@@ -32,6 +32,7 @@ The following arguments are supported:
 
 - `project_id` - (Required) The Project ID.
 - `name` - (Required) The name of the Team.
+- `top` - (Optional) The maximum number of teams to return.
```
Comment (xuzhang3) [inline website/docs/d/data_team.html.markdown]:
```suggestion
- `top` - (Optional) The maximum number of teams to return. Defaults to `100`.
```

**Review by xuzhang3 — CHANGES_REQUESTED** [review]

**Comment by xuzhang3** [comment]
@ricardosequeira LGTM 🚢

**Review by xuzhang3 — APPROVED** [review]
