### PR TITLE
`azuredevops_group(s)`: Added filter to only filter out project-scoped groups when `project_id` is specified

### LINKED ISSUE #1517: azuredevops_group and azuredevops_groups data sources may return collection-level groups when project_id is specified
### Community Note

* Please vote on this issue by adding a :+1: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.13.5
Azure DevOps Provider v1.13.0

### Affected Resource(s)

* `azuredevops_group` (data source)
* `azuredevops_groups` (data source)

### Terraform Configuration Files

```hcl
data "azuredevops_group" "readers" {
  project_id = data.azuredevops_project.example.id
  name       = "Readers"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

When using `azuredevops_group`, the data source should return the project-level `[ProjectName]\Readers` group, since a `project_id` is explicitly provided.

When using `azuredevops_groups`, only project-scoped groups should be returned when a `project_id` is specified.

### Actual Behavior

- `azuredevops_group`: returns a collection-level group with the same display name instead of the project-scoped group.
- `azuredevops_groups`: includes collection-level groups in the results alongside project-scoped groups.

### Steps to Reproduce

1. Create (or have) a collection-level group with the same name as a built-in project group (e.g. "Readers")
2. Use the `azuredevops_group` data source with a `project_id` and `name = "Readers"`
3. `terraform apply`
4. Observe the returned group is the collection-level group, not the project-scoped one

### Important Factoids

**Root Cause Analysis:**

In [`data_group.go` - `getGroupsForDescriptor`](https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/graph/data_group.go), when `projectDescriptor` is provided, all groups returned by the API are included **without domain filtering**:

```go
} else {
    groups = append(groups, *newGroups...)
}
```

In contrast, when `projectDescriptor` is empty (collection-level query), the code **does** filter groups by their `Domain` field (lines 138-151) to ensure only collection-scoped groups are returned.

The Azure DevOps Graph API `ListGroups` with a project scope descriptor can return collection-level groups that have visibility within the project. The `selectGroup` function then returns the **first** group matching by `DisplayName`, regardless of scope:

```go
func selectGroup(groups *[]graph.GraphGroup, groupName string) *graph.GraphGroup {
    for _, group := range *groups {
        if strings.EqualFold(*group.DisplayName, groupName) {
            return &group
        }
    }
    return nil
}
```

If a collection-level group with the same name appears before the project-level group in the API response, the wrong group is returned.

**Suggested Fix:**

When `projectDescriptor` is not empty, filter the returned groups to only include those whose `Domain` matches the project scope (e.g. `vstfs:///Classification/TeamProject/{project-id}`). This mirrors the filtering already in place for collection-level queries. Both `azuredevops_group` and `azuredevops_groups` use the shared `getGroupsForDescriptor` function, so the fix would apply to both. Related: #485 / PR #486 which added the collection-level domain filtering.

### References

* #485 - AzureDevops Group not found (inverse of this issue — collection groups were filtered too aggressively)
* [`data_group.go` - `getGroupsForDescriptor`](https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/graph/data_group.go)

### PR DESCRIPTION
**Pull request by v-kenntan**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## Description

Added filter to only filter out project-scoped groups when project_id is specified for azuredevops_group and azuredevops_groups. Currently when a project id is specified, all groups are included regardless of scope.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Test Result
<pre>
TF_ACC=1 go test -v -run='TestAccGroupsDataSource_' ./azuredevops/internal/acceptancetests
=== RUN   TestAccGroupsDataSource_Read_Project
=== PAUSE TestAccGroupsDataSource_Read_Project
=== RUN   TestAccGroupsDataSource_Read_NoProject
=== PAUSE TestAccGroupsDataSource_Read_NoProject
=== RUN   TestAccGroupsDataSource_ProjectID_FiltersOutCollectionGroups
--- PASS: TestAccGroupsDataSource_ProjectID_FiltersOutCollectionGroups (28.26s)
=== CONT  TestAccGroupsDataSource_Read_Project
=== CONT  TestAccGroupsDataSource_Read_NoProject
--- PASS: TestAccGroupsDataSource_Read_NoProject (12.50s)
--- PASS: TestAccGroupsDataSource_Read_Project (29.05s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        57.319s
</pre>

<pre>
TF_ACC=1 go test -v -run='TestAccGroupDataSource_' ./azuredevops/internal/acceptancetests
=== RUN   TestAccGroupDataSource_Read_HappyPath
=== PAUSE TestAccGroupDataSource_Read_HappyPath
=== RUN   TestAccGroupDataSource_Read_ProjectCollectionAdministrators
=== PAUSE TestAccGroupDataSource_Read_ProjectCollectionAdministrators
=== RUN   TestAccGroupDataSource_ReadersResolvesWithProjectID
--- PASS: TestAccGroupDataSource_ReadersResolvesWithProjectID (25.28s)
=== CONT  TestAccGroupDataSource_Read_HappyPath
=== CONT  TestAccGroupDataSource_Read_ProjectCollectionAdministrators
--- PASS: TestAccGroupDataSource_Read_ProjectCollectionAdministrators (3.76s)
--- PASS: TestAccGroupDataSource_Read_HappyPath (24.56s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        49.847s
</pre>

## Related Issue(s)

Fix #1517

### CODE REVIEW

File: azuredevops/internal/service/graph/data_group.go [hunk 1]
```diff
@@ -150,7 +151,12 @@ func getGroupsForDescriptor(clients *client.AggregatedClient, projectDescriptor
 				}
 				groups = append(groups, filteredGroups...)
 			} else {
-				groups = append(groups, *newGroups...)
+				for _, grp := range *newGroups {
+					if grp.Domain != nil && strings.Contains(*grp.Domain, projectID) {
```
Comment (magodo) [inline azuredevops/internal/service/graph/data_group.go]: Instead of matching the exact project by its id (hence requiring the `projectID`), shouldn't it be enough to just match the `domain` prefix with: `vstfs:///Classification/TeamProject/`?

File: azuredevops/internal/acceptancetests/data_group_test.go [hunk 2]
```diff
@@ -58,6 +58,32 @@ func TestAccGroupDataSource_Read_ProjectCollectionAdministrators(t *testing.T) {
 	})
 }
 
+func TestAccGroupDataSource_ReadersResolvesWithProjectID(t *testing.T) {
```
Comment (magodo) [inline azuredevops/internal/acceptancetests/data_group_test.go:62]: These new tests here need to explicitly:

> Create (or have) a collection-level group with the same name as a built-in project group (e.g. "Readers")

Otherwise, even without this change, these tests can pass?

**Review by magodo — CHANGES_REQUESTED** [review]
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

File: azuredevops/internal/acceptancetests/data_group_test.go [hunk 3]
```diff
@@ -80,3 +104,70 @@ data "azuredevops_group" "test" {
...
+  project_id = azuredevops_project.test.id
+}
+
+resource "azuredevops_group_membership" "make_collection_visible" {
+  mode  = "add"
+  group = data.azuredevops_group.project_admins.descriptor
+  members = [
+    azuredevops_group.collection_readers.descriptor
+  ]
+}
```
Comment (magodo) [inline azuredevops/internal/acceptancetests/data_group_test.go:129]: Could you please guide me why this is necessary?

File: azuredevops/internal/acceptancetests/data_group_test.go [hunk 4]
```diff
@@ -80,3 +104,70 @@ data "azuredevops_group" "test" {
...
+
+data "azuredevops_group" "project_readers" {
+  name       = "Readers"
+  project_id = azuredevops_project.test.id
+  depends_on = [azuredevops_group_membership.make_collection_visible]
+}
+
+data "azuredevops_groups" "project_groups" {
```
Comment (magodo) [inline azuredevops/internal/acceptancetests/data_group_test.go]: This is for the groups data source, shouldn't appear in this group test file.

File: azuredevops/internal/acceptancetests/data_groups_test.go [hunk 5]
```diff
@@ -65,3 +84,38 @@ data "azuredevops_groups" "groups" {
...
 	return `data "azuredevops_groups" "groups" {}`
 }
+
+func hclGroupsDataProjectScopedConfig(projectName string) string {
+	return fmt.Sprintf(`
+resource "azuredevops_project" "test" {
+  name = %q
+}
+
+data "azuredevops_groups" "scoped" {
```
Comment (magodo) [inline azuredevops/internal/acceptancetests/data_groups_test.go]: This test case shall also make the group to duplicate at project and collection level to verify the logic actually works.

**Review by magodo — CHANGES_REQUESTED** [review]

File: azuredevops/internal/acceptancetests/data_group_test.go (hunk 3 above)
Comment (v-kenntan) [reply azuredevops/internal/acceptancetests/data_group_test.go:129]: Hi, it's to ensure that the collection scoped `azuredevops_group` is visible to the project scoped data sources of `azuredevops_project`, before we process the project scoped data sources

File: azuredevops/internal/acceptancetests/data_groups_test.go [hunk 6]
```diff
@@ -65,3 +88,70 @@ data "azuredevops_groups" "groups" {
...
+
+resource "azuredevops_group_membership" "make_collection_visible" {
+  mode  = "add"
+  group = data.azuredevops_group.project_admins.descriptor
+  members = [
+    azuredevops_group.collection_readers.descriptor
+  ]
+}
+
+data "azuredevops_group" "project_readers" {
```
Comment (magodo) [inline azuredevops/internal/acceptancetests/data_groups_test.go]: Is this needed?

**Review by magodo — CHANGES_REQUESTED** [review]

**Review by magodo — APPROVED** [review]
```shell
💤 TF_ACC=1 go test -v -run='TestAccGroupDataSource_' ./azuredevops/internal/acceptancetests
=== RUN   TestAccGroupDataSource_Read_HappyPath
=== PAUSE TestAccGroupDataSource_Read_HappyPath
=== RUN   TestAccGroupDataSource_Read_ProjectCollectionAdministrators
=== PAUSE TestAccGroupDataSource_Read_ProjectCollectionAdministrators
=== RUN   TestAccGroupDataSource_ReadersResolvesWithProjectID
--- PASS: TestAccGroupDataSource_ReadersResolvesWithProjectID (61.49s)
=== CONT  TestAccGroupDataSource_Read_HappyPath
=== CONT  TestAccGroupDataSource_Read_ProjectCollectionAdministrators
--- PASS: TestAccGroupDataSource_Read_ProjectCollectionAdministrators (4.00s)
--- PASS: TestAccGroupDataSource_Read_HappyPath (26.56s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        88.052s

💤 TF_ACC=1 go test -v -run='TestAccGroupsDataSource_' ./azuredevops/internal/acceptancetests
=== RUN   TestAccGroupsDataSource_Read_Project
=== PAUSE TestAccGroupsDataSource_Read_Project
=== RUN   TestAccGroupsDataSource_Read_NoProject
=== PAUSE TestAccGroupsDataSource_Read_NoProject
=== RUN   TestAccGroupsDataSource_ProjectID_FiltersOutCollectionGroups
--- PASS: TestAccGroupsDataSource_ProjectID_FiltersOutCollectionGroups (61.00s)
=== CONT  TestAccGroupsDataSource_Read_Project
=== CONT  TestAccGroupsDataSource_Read_NoProject
--- PASS: TestAccGroupsDataSource_Read_NoProject (17.23s)
--- PASS: TestAccGroupsDataSource_Read_Project (29.89s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        90.891s
```
